### ISSUE TITLE
the docker restart 

### ISSUE THREAD

**Issue by overflow-ITA** [ibehren1/fw-gui#53]
Hi, i installed with docker compose Docker Compose Minimal (just FW-GUI and MongoDB no TLS), but fw-gui restart with this error .

**Describe the bug**
the docker restart , in the log have this

ValueError: invalid literal for int() with base 10: ''

2024-10-23 09:47:29,025:INFO:<module>	Logging Level: INFO

Traceback (most recent call last):

  File "/opt/fw-gui/app.py", line 150, in <module>

    minutes=int(os.environ.get("SESSION_TIMEOUT"))

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**To Reproduce**

install with docker compose 
docker compose -f  /home/vyos-fw-gui.yml up -d

thank for you great work

**Comment by ibehren1** [comment]
Howdy @overflow-ITA!

Thanks for reporting the issue you have encountered.

I have reproduced the and I think the quick answer is to make sure that you are supplying an integer value for `SESSION_TIMEOUT` rather than having it be blank.

```
      - SESSION_TIMEOUT=120
```

or full version:

```yaml
version: '3.7'
services:
  fw-gui:
    image: ibehren1/fw-gui:latest
    container_name: fw-gui
    depends_on:
      - mongodb
    environment:
      - APP_SECRET_KEY='This is the secret key.'
      - DISABLE_REGISTRATION=False
      - MONGODB_URI=mongodb
      - BUCKET_NAME=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - SESSION_TIMEOUT=120
    ports:
      - 8080:8080/tcp
    restart: unless-stopped
    volumes:
      - data:/opt/fw-gui/data
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
volumes:
  data:
  mongo-data:
  mongo-config:
```

Please test this and let me know if it resolves your issue.

Separately, I will see if I can address a blank value in the code.
Isaac
